name: Python new CI

on:
  push:
    branches:
      - Master

permissions:
  id-token: write   # This is required for requesting the JW
  contents: read    # This is required for actions/checkout

jobs:
  python-ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
         python-version: 3.12.0-alpha.7 
         architecture: x64
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
      - name: Get version from file
        run: |
          VERSION=$(cat version.txt)
          echo "Version is $VERSION"
          echo "::set-output name=version::$VERSION"
        id: version
        
      - name: Zip Python code
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          GIT_COMMIT=$(echo $GITHUB_SHA | cut -c1-7)
          VERSION=${{ steps.version.outputs.version }}
          FILE_NAME="$REPO_NAME-$GIT_COMMIT-$VERSION.zip"
          echo "Creating archive $FILE_NAME"
          zip -r $FILE_NAME src/main/python/helloworld.py
